### ISSUE TITLE
Cactus signs not working 1.18.1 supplementaries-1.1.8

### ISSUE THREAD

**Issue by Tyronadre** [MehVahdJukaar/Supplementaries#186] opened 2022-01-13 16:49 UTC
Parsing error loading recipe supplementaries:hanging_signs/hanging_sign_cactus
com.google.gson.JsonSyntaxException: Unknown item 'structurize:blockcactusplank'
        at net.minecraft.world.item.crafting.ShapedRecipe.m_151280_(ShapedRecipe.java:276) ~[server-1.18.1-20211210.034407-srg.jar%23172!:?] ...
        
Isn't in structurize anymore. They switch it to a new mod. Block now called: domum_ornamentum:cactus_extra (or domum_ornamentum:green_cactus_extra)

**Comment by MehVahdJukaar** [comment] 2022-01-15 20:23
I removed it and added the new one. didn't test this properly but hopefully it should work

**Comment by LeoBeliik** [comment] 2022-02-04 19:58
I can confirm this is still a problem in **supplementaries-1.18.1-1.1.11**
[Latest Log](https://gist.github.com/LeoBeliik/7b79c88b9cd6ab4701286ef570e1e4b3)
![2022-02-04_16 54 16](https://user-images.githubusercontent.com/11804768/152594823-bd256b11-a712-4421-b622-9fb5507e1d4b.png)
![2022-02-04_16 54 15](https://user-images.githubusercontent.com/11804768/152594851-a3c53c31-25e5-45d2-a66e-04b4a250e706.png)

**Comment by MehVahdJukaar** [comment] 2022-02-17 01:34
supposedly fixed in 1.2.0 since the whole sign system changed

**Closed** 2022-02-21 21:13 UTC
