### ISSUE TITLE
[Forge 1.19.2] Breaking textures when used with EMF and ETF

### ISSUE THREAD

**Issue by Aulberon** [MehVahdJukaar/Supplementaries#644] opened 2023-06-09 22:58 UTC
When using ETF/EMF to render custom entity models, if Supplementaries is present, the textures of the entity shift as seen in the image below.

Tried an instance with only the important mods(ETF, EMF, Moonlight and Supplementaries) but the problem persisted.

![image](https://github.com/MehVahdJukaar/Supplementaries/assets/39103311/4a041a52-16d1-4363-8a9c-d3032cb53545)

**Comment by MehVahdJukaar** [comment] 2023-06-10 08:17
Just endermen?

**Comment by MehVahdJukaar** [comment] 2023-06-10 09:05
I heard people using it with fresh animations for example with no issues

**Comment by Aulberon** [comment] 2023-06-10 11:29
Yes, only the endermen seens to present this problem. I have tried with other mobs and all seens fine. 
I'm also using Fresh Animations and it works perfectly, the only problem seens to be the endermen having new textures. 
I'm using a modified version of the Enhanced Enderman resource pack, here is a copy if you need it.
[Enhanced+Endermans.zip](https://github.com/MehVahdJukaar/Supplementaries/files/11712295/Enhanced%2BEndermans.zip)

**Comment by Aulberon** [comment] 2023-06-10 11:35
Here is a print of how it looks without supplementaries.
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/39103311/d28272f8-20a7-4c72-9cb0-a34b3623f3a7)

**Comment by MehVahdJukaar** [comment] 2023-06-10 13:57
weird im not even touching the enderman renderer nor model

**Comment by MehVahdJukaar** [comment] 2023-06-10 13:58
also a texture change should always be compatible if it has the same dimensions and such

**Comment by MehVahdJukaar** [comment] 2023-06-10 14:06
the only thing that must be is the enderman heads i have in the mods. I'm adding those using forge EntityRenderersEvent.CreateSkullModels event.  I'm not familiar with the mod but could it be that said mods are ports of some fabric mod? if so I would assume that somebody didnt do their job properly as if this is the case they arent compatible with forge own api itself

**Comment by MehVahdJukaar** [comment] 2023-06-10 14:09
tho tbh i doubt thats the case so idk

**Comment by Xelbayria** [comment] 2023-10-18 16:56
is the issue resolved? if yes, then please close. 
I'm not sure if this is related to supplementaries

**Comment by Barerock** [comment] 2024-07-10 19:09
Others in the Fresh Animations discord report the Enderman head specifically being broken by Supplementaries, and there are a few bug reports that note that Supplementaries sometimes affects the entire resource pack Fresh Animations, though I believe that to specifically be their order of files, not this mod's fault.

A common bug, which I have as well, is that Supplementaries will replace/mess up the rendering of the Enderman's head because of the way it's added into the mod, regardless of being enabled or not. In my case it appears as a regular Enderman with full animation support, but with no face and a hollow head. This is also the case for the Supplementaries Enderman Head item, which is what leads me to believe that its implementation specifically is what is causing this issue.

**Comment by Barerock** [comment] 2024-10-12 05:07
I've since tested this as well and found that it's caused by FA and Supp together. Super creepy, this is what mine looks like:
![image](https://github.com/user-attachments/assets/2c9f3968-2d89-41bd-b114-8b406d25fd72)

**Comment by MehVahdJukaar** [comment] 2024-10-13 10:42
This is definitely not my issue. I will be closing this. Supplementaries merely reads the existing enderman model. It does not modify it in any way

**Closed by MehVahdJukaar** 2024-10-13 10:42 UTC
Labels: bug, 1.19.2
