### ISSUE TITLE
[🐞]: Crash with fabric version of farmer's delight

### ISSUE THREAD

**Issue by IamKayrox** [MehVahdJukaar/Supplementaries#1000] opened 2024-03-27 17:40 UTC
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FABRIC

### Supplementaries Version

1.20-2.8.9

### Moonlight Lib Version

fabric_1.20-2.11.9

### Issue Detail

On launch a messages says that Supplementaries is incompatible with versions below 2.0 of Farmer's Delight but the newest version available of Farmer's Delight on Fabric is 1.4.3

**Comment by RowanBee** [comment] 2024-03-27 17:40
Same issue, 
![image](https://github.com/MehVahdJukaar/Supplementaries/assets/47164828/c591ad76-3e35-4714-b96d-43183b3aa35b)

**Comment by MehVahdJukaar** [comment] 2024-03-27 20:08
duplicate of 999
Sad since this was the 1k issue

**Closed by MehVahdJukaar** 2024-03-27 20:08 UTC
Labels: bug
