### ISSUE TITLE
[❓]: What is supplimentaries doing?

### ISSUE THREAD

**Issue by funnycubeguy** [MehVahdJukaar/Supplementaries#1199] opened 2024-11-08 20:42 UTC
### Your Question

What is it doing with mixins?

### Detail

https://pastes.dev/KtAGidWyDs

I noticed it breaks with every performance optimization mod. what is happening here? ty
happens after the 3.0.0 update

**Comment by MehVahdJukaar** [comment] 2024-11-08 21:18
"it breaks"
no, they break because of a bug they had and its been verified and confirmed yet wont be fixed in 1.20 as they dont update old versions for some reasons, not even 1.21 aparently
Still next update will use lithium featuretoggle which will toggle that optimization that caused the crash. 
I'll say againthis is not supplementaries fault and you should not be opening issues here for this

**Comment by MehVahdJukaar** [comment] 2024-11-08 21:20
oh nevermind i thought you were referring to lithium issue
 
 You are actually using mohist!!!
 
 this mod is for either forge or fabric. wether it works on those loaders is entirely up to them. This is not my issue.
 
 needless to say nobody should ever used those "hybrid" loaders. Just use forge mods! This is precisely why, there WILL be issues, the fact that you didnt have before is merely chance or maybe they were just misbehaviors graphical or whatnot

**Comment by MehVahdJukaar** [comment] 2024-11-08 21:23
mods are built for forge or fabric. mohist is a different loader, source code is different. This issue for example is complaining a minecraft class from not being there?? how? because source code is different and not the loader it was built for.
Just use mods, there is literally nothing they cant do

**Comment by MehVahdJukaar** [comment] 2024-11-08 21:31
mohist is a hack basically, any issue or discrepancy that it has against forge its up to them to fix. Modders know how a headache that is and most just refuse to have anything to do with it.
With the way it is done i know it has so many potential issues as, just like the terribly infamouse optifine, it alters the source code so thats just setting a minefield for modded mixins, a cathastrophe waiting to happen with the right mod and unfortunate enough target

**Closed as completed** 2024-11-08 21:58 UTC
