### ISSUE TITLE
Crash in 1.18.2 related to vines?

### ISSUE THREAD

**Issue by DesertDweller** [MehVahdJukaar/Supplementaries#344] opened 2022-08-28 00:30 UTC
Mod Version: idas_forge-1.4.1+1.18.2, Forge 40.1.73

Crash when generating idas:treetop_tavern structure in certain seeds.
[crash-2022-08-27_10.49.44-server.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9438861/crash-2022-08-27_10.49.44-server.txt)

I created a Curseforge modpack with nothing but IDAS and its dependencies (one of which is Supplementaries).
Make new Creative world with seed 1165080016, then /tp 2832 150 700.
Game will crash trying to generate the structure.
Seems to be some interaction with vines with existing terrain?
Structure contains lots of vines too.
Generating worlds with random seeds yields about 20% of seeds will experience the problem (/locate idas:treetop_tavern, then /tp there).

Also opened issue on the IDAS page as well.

**Comment by MehVahdJukaar** [comment] 2022-08-28 11:15
Hm so I do have a mixin that allows vines to be placed under more blocks and this issues happens right there, however what I do is checking a tag which should never fail and infact isnt what is on that mast method call which seem to revolve around the vanilla method which checks the hitbox of what's above. It seems that somehow during worldgen those vines have a null hitbox. Could you try to open the mod jar with with rar and remove the VineMixin line from the mixins jsons? If it still happens without that we know that it's not that one

**Comment by Skinklizzard** [comment] 2022-09-12 11:34
as far as I can tell similar thing happens with rope blocks/rope knots
https://github.com/The-Nexus-Project/Limitless-5/issues/186

crash report: https://pastebin.com/KKAHxKkz

**Comment by MehVahdJukaar** [comment] 2022-09-12 13:21
That's a pretty different thing and this time involves one of my blocks. What block was contained in those?

**Comment by Skinklizzard** [comment] 2022-09-12 19:29
> That's a pretty different thing and this time involves one of my blocks. What block was contained in those?

ah sorry then, I can create a new issue if required.
once the region spawned in SP the only ropes in the area were part of an idas castle
![2022-09-12_21 24 38](https://user-images.githubusercontent.com/16168842/189739027-f65fc75e-f86e-47eb-880a-d025fc9f51f1.png)
![2022-09-12_21 25 09](https://user-images.githubusercontent.com/16168842/189739032-0d42909b-543a-4231-8b19-a89d763cad32.png)

it appears some of the ropes are attempting to connect to nothing or something with an empty collision box

**Comment by ShadeKage** [comment] 2022-10-22 03:09
> Skinklizzard
I know what may be the cause
#416
If you have farmers harvest in your mod pack, make sure its the NEWEST version
If not then your crash file mentions " biomesoplenty:trees_ominous_woods "
likely meaning thats causing your issue as well
if not that as well, then i got nothin else for ya, good luck on your pack

**Comment by MehVahdJukaar** [comment] 2022-11-04 09:43
This happened when during worldgen stuff like vines feature was trying to access rope know block shape. Fixed in latest versions

**Closed by MehVahdJukaar** 2022-11-04 09:43 UTC
