### ISSUE TITLE
[1.16.5] better animals plus butterfly and supplementaries flax crashes server

### ISSUE THREAD

**Issue by xinwolfthorn** [MehVahdJukaar/Supplementaries#397] opened 2022-10-06 03:25 UTC
https://pastebin.com/SabPuNyw

when i pick up the butterfly that the error lists, the server doesn't crash anymore

**Comment by MehVahdJukaar** [comment] 2022-10-06 11:48
A butterfly is trying to incorrectly set the age of a flax block. I did work around this in future version but I don't think the issue is really on my end. Also I haven't updated 1.16 in almost a year

**Comment by Kasualix** [comment] 2023-08-29 03:44
This is not supplementaries's fault and has been fixed in betteranimalplus.

**Closed** 2023-08-29 05:35 UTC
