### ISSUE TITLE
1.16.5 - 36.2.2 - 0.15.2 - Server "Failed to store chunk"

### ISSUE THREAD

**Issue by Snaitf** [MehVahdJukaar/Supplementaries#95] opened 2021-08-12 23:06 UTC
Minecraft: 1.16.5
Forge: 36.2.2
Supplementaries: 0.15.2
Selene: 1.6

Server will not save any chunks when this mod is loaded.  Tested with Supplementaries and Selene only.

Debug Log:
https://hastebin.com/ahutigowul.yaml

**Comment by asiekierka** [comment] 2021-08-13 08:50
The issue is that the structure `net.mehvahdjukaar.supplementaries.world.structures.WaySignStructure`'s feature name getter returns null - that implies it's not properly registered with Forge.

Duplicate of https://github.com/MehVahdJukaar/Supplementaries/issues/93

**Comment by DPurple** [comment] 2021-08-13 10:39
Well , in net.minecraft.world.gen.feature.structure.Structure.java line 235
getFeatureName() is using STRUCTURES_REGISTRY which only touched by vanilla structures.
DeferredRegister one only simple use setRegistryName for forge itself but didn't touch STRUCTURES_REGISTRY 
so calling super.getFeatureName() will result null because it doesn't exists in STRUCTURES_REGISTRY.
I think this should be a bug of forge, the solution is using forge registry in WaySignStructure.getFeatureName() instead of super.getFeatureName()

**Comment by DPurple** [comment] 2021-08-13 10:56
I think this may fix the problem but ugly...
```
    @Override
    public String getFeatureName() {
        retrun net.minecraftforge.registries.ForgeRegistries.STRUCTURE_FEATURES.getKey(this).toString();
    }
```

**Comment by DPurple** [comment] 2021-08-13 12:13
Sorry I think simple patch getFeatureName() is not a good idea which ChunkSerializer tried to use STRUCTURES_REGISTRY too, and locate command.
Have correct STRUCTURES_REGISTRY should be important...

**Comment by MehVahdJukaar** [comment] 2021-08-13 19:09
Fixed in 0.15.2b

**Closed by MehVahdJukaar** 2021-08-13 19:09 UTC
