### ISSUE TITLE
[🐞]: Console errors about 'Slimed'

### ISSUE THREAD

**Issue by DracoHero** [MehVahdJukaar/Supplementaries#1216] opened 2024-11-14 03:35 UTC
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries 1.20-3.1.5

### Moonlight Lib Version

moonlight 1.20-2.13.25

### Issue Detail

I get these errors in the console that tell me about '[Supplementaries/]: !!!!Failed to add slimed layer to entity:', I have disabled the 'Slimed' option and it still appears, is there a way to remove it? ? Thank you...

[latest.log](https://github.com/user-attachments/files/17742453/latest.log)

**Comment by MehVahdJukaar** [comment] 2024-11-14 09:55
Yes, update forge to neoforge as it's a forge bug

**Comment by serioos** [comment] 2024-11-17 14:29
I have this problem too. It floods the log with A LOT of slimed errors even though I turn off everything slime related in the configs like overlay and being throwable and the like.

[Supplementaries Slimed Errors.txt](https://github.com/user-attachments/files/17790838/Supplementaries.Slimed.Errors.txt)
[latest.log](https://github.com/user-attachments/files/17790839/latest.log)

Minecraft 1.20.1
Forge 47.3.12
supplementaries-1.20-3.1.7.jar
suppsquared-1.20-1.1.16.jar
amendments-1.20-1.2.12.jar

**Comment by DelviousCrafts** [comment] 2024-11-20 05:13
> Yes, update forge to neoforge as it's a forge bug

If it's a known bug for a launcher that you have no intention of updating as this response so obviously implies, why is this broken update released for forge at all? Leave the forge update where it actually works and update only for neoforge update with the new info. This angers me so much about you particularly as a mod author, but other mod authors are also guilty of it. You are the worst of the culprits, but far from the only one.

You have a very not-my-problem-type attitude and seem to not give a single shit about your audience. You, specifically, have made me not report ANY bugs to anyone due to the fact that you're so abrasive and dismissive about your responses. If it works in your development area and a mod hasn't updated yet, your solution is "fuck you update to the new thing anyway. Screw that mod." The ONLY reason ANY of your mods are even remotely used by me anymore is due to the insane amount of integration that already exists that would require a complete rewrite of my pack which has take 2+ years, which trust me I have heavily considered.

I understand you're doing this of your own free will and time. But keep in mind that not everyone has the free time that you do and many mods can't update at your speed. If it's not going to work on a specific launcher or on a specific version, stop updating that version and breaking it and absolutely refusing to fix it in that you revert your changes for that version and stop updating.

Rant over

**Comment by MehVahdJukaar** [comment] 2024-11-20 06:35
- "no intention of updating". I am constantly updating 1.20
- "broken update" . Nothing about it is broken. Bug is from forge itself. Mod doesn't crash and works as intended
- my attitude is I won't attempt to make hacky shitty workarounds into other mod code to try to fix issue THEY caused as those would be super brittle and hard to do. This "issue" is an exception, since bug comes from forge I have a workaround there so I merely log that something went wrong and proceed as normal
- "not give a shit about your audience" I have been known in the past for my speed at fixing stuff and I'm constantly implementing user suggestions, sometime from one day to the other
- "mods can't update at your speed" understandable but you say as if my update speed is an issue
- "break" you keep on using that word but I don't see anything breaking here, this issue is about a simple annoyance at most for the few people that read their logs, one of 2 log lines won't harm anymody. Besides this just happens when a mod adds a renderer that dies not inherit from living entity renderer which rarely happens too

Honestly I'm just wondering why you are so pissed about some log lines

**Comment by DelviousCrafts** [comment] 2024-11-20 08:34
Well considering the issue with slime has cause me to be unable to update since implementation as this exact same error would come up when attempting to connect to a server and refused connection due to a illegal argument exception. Every update that's pushed since then I try yet again, and am met with failure. It's due to the update that also introduced the slime overlay and slime functionality because that started when the reported issue became a problem and now either I choose to update and never play with friends, remove the mods that are an issue against your one (there are 6 in my pack alone), or not update and have the bugs that were fixed since then. It's very much so a broken update.

My response and primary source of frustration was about the fact that you seemingly brushed off their report entirely because they're using forge instead of the latest and greatest and as such it's not worth your time to see if you can either find a workaround, or at worst remove that portion from the forge version.

Yes I'm aware that me not reporting is an issue. For over a decade I had the same mentality that bugs must be reported or they can't be fixed. YOU made the process of reporting so incredibly annoying and unfruitful that I stopped and refused to report anywhere anymore because more and more authors had begun gaining the same attitude of eliteism and it's starting to piss me off. If you're not well known in the development community, your opinion anymore appears to be worth less than dog shit, where that didn't used to be the case.

Your speed isn't an issue, it's your unwillingness to maintain previous versions that not a majority have updated from AND your unwillingness to address issues that are created by your "fixes" for those issues causing further issues ON TOP OF your blind sightedness of seeing that maybe you did accidently mess something up. Even your responses made your code seem godly and all others are trash. If it's broken, they broke it, not you. Period end of story.

It's not the 1.20 portion, but the refusal to acknowledge that the issue is an issue in the forge portion because it's forge and forge is broken. While yes forge does have some broken portions, there are many mods that haven't updated to neoforge yet, or to 1.20.1 where a more stable version of neoforge actually exists.

Your examples have also not been my experience across your entire mod array reporting thus far. If it was a one off happening or I had actually made a stupid mistake, it wouldn't have been an issue. But nearly every report I've made it's been "another mods fault" and yet in a future update for your mod with no changes to the one that's broken whtsoever, and no mention of my report in the changelog, nor a closure or even a repose to the ticket I created, therefore leading me to believe you didn't even know you'd fixed it accidentally. Most responses I've received to my reports made it painfully clear that you had no intention of even looking into the issue because you saw another mod as the culprit and your code is infallible until proven otherwise by yourself or someone else.

Did I go overboard with my rant?Abso-fucking-lutely, but considering my experience with you in particular when it comes to reporting anything, when I came to try and give reporting one last chance and make a report, I find that my issue was already reported and dismissed as "not your problem."

Am I saying you should fix every mod ever that could possibly interact with yours? Absolutely not, that's assenine. What I'm saying is don't auto ignore an issue just because it's not immediately obvious that your code is the culprit and don't auto dismiss a report as frivolous just because that person didn't mention something else that happened from the same issue because they didn't know about it. or when something like this gets reported, and you find that it's something big like an issue with forge, remove the offending code to repair at least that particular version of you have no intention of continuing to maintain that version aside from game breaking issues. An issue is an issue and who knowss what other issues that aren't seen are being caused by ones that are seen.

"Sorry you want the newest stuff, you should be following the latest versions of things" is a far more acceptable attitude than "you want the mod to work at all? Move on from every mod that hasn't had a chance to update yet and go to the latest thing even though most mods haven't updated to that yet."

**Comment by MehVahdJukaar** [comment] 2024-11-20 08:50
That is NOT this issue then. Whichever you are having you should open a new issue posting your log. This issue is 1: client side, 2: happens on game load not server join, 3: merely a log line, can't do the thing you describe

**Comment by DelviousCrafts** [comment] 2024-11-20 08:53
I'm fully aware this issue is not the same as my issue. That's not remotely what any of this was about. This was about the fact that you dismissed an issue as not an issue because you see another mod as inferior and refuse to even remove the offending code, just leave it and have it be annoying. You brushed it off when who knows what kind of background issues are happening because of it. Maybe it's time to reexamine that part of the code. And no I will not be submitting a new issue thank you.

**Comment by DelviousCrafts** [comment] 2024-11-20 09:01
And the fact that you didn't even take the time to read thoroughly enough to know that I was ranting about your attitude, not the issue I originally came here to report makes my point even more thoroughly. You didn't care enough to read the issue. You grazed, and blamed an entirely unrelated thing that you saw as the culprit. And I'll bet that the issue goes unresolved too.

**Comment by MehVahdJukaar** [comment] 2024-11-20 09:17
As for the wall of text let's go over it again.
- I brushed off this issue so quickly as it's not an issue, it's just a couple of lines in the log. It doesn't cause any harm and it's only there for information purposes. What the log and me is saying us basically that due to a forge bug the slime overlay can't be applied to the selected entity and I can't do nothing about it, so the entity will be ignored. Use latest neoforge if you want this to work there, if not it's just a log line saying that a minor feature will be off.
- "it's very much a broken update". This kind of attitude is not constructive at all. You so fare have not reported any issue of your own yet are complaining about one. Make a new issue and we'll see what that one is about. So far hundreds of people have used the mod no problem and the ones that did have issues have had them fixed very quickly after they got reported. I can NOT fix issues that are not reported. I can't test ALL possible mods people could install, that's a ludicrous request 
- "my unwillingness to maintain previous version". Couldn't be further from the truth. As I've literally just told you I am updating 1.20 almost daily. On top of that I am maintaining 1.21 AND fixing any critical bug that comes up in 1.19 from time to time
- being well known or not in the community or not has little to do as this has not to do with anybody's "opinion". When analyzing an issues there are certain facts, not opinion. If I were to write a mod that passes a null parameter to a vanilla method that does not accept null it wouldn't be some authors "opinion" that my code is wrong, it would be a fact
- for the next block do you realize you aren't talking about any particular issue here? You make it sound like I just told you to report some issue to another mod because you thought I had said something like "oh if course it's their issue, how could it POSSIBLY an issue from my own perfect code". For the sake of arguments let's say I did tell you to report to somebody else. In that case how can you blame me for it? When an issue is reported I have to look into it and that takes time, sometimes the issue is of unknown origin so both authors must be reported, other times I can easily see it's in my end and it will be likely be fixed within hours if it involves a crash. If I however see that it's caused by some other mod code I would simply tell users to report there. The fact that you imply that whichever issue we're to occur would ALWAYS be considered an issue I have (because of course it is, the game ran fine before thr update) outlines you don't have much knowledge if how modding and coding works. Take that null example from before. Say my update implemented that method and used that object. Oopsies then a null pointer exception would be thrown because some other mod had thrown a null there in a method that does not accept it, which, even tho in vanilla might not crash as that particular object was no used, a mod could and the method signatures prohibits that thus it would not be my issue
- about your reports sounds like you made others in the past that were not closed. Which are they? I have so many I forget to close them as I prefer having users do it when they verify that in their setup the issue was closed. As for the change log I agree they can be vague as I tend to mention the source of the bug fixed rather than the consequence. Regardless if any issue you have had was not fixed feel free to sollicit it, you have no ideas how many reports I get daily across all my mods, be it feature requests, questions or actual mod compat issues

Finally I'll say again that out of all the issues you could have picked to post this rant you picked the worst one. As this is not an issue. I could remove those log lines tomorrow. that was the complaint, not that the slimed overlay didnt work on those mobs (I cant get ut to work as as ive said the forge event is broken for some entities) but I can remove the log lines that apparently annoy users warning them about it. Mere log lines that don't cause any gameplay issues at all

**Comment by DelviousCrafts** [comment] 2024-11-20 10:25
Responding to each bullet in kind in order of bulletpoints.

- It's not an issue in that it won't crash, yes. For modpack authors such as myself who are digging through the console for errors we've created in our own code. Console spam like this is a nightmare. I have 6 mods that are erroring with your slime overlay. Each one with at least six mobs, none of which have the slime overlay work. That's a minimum of 36 gigantic blocks of console logs I have to dig through to make sure they are not my issue but yours then skip past every time I need to get to my section of error codes. And that's just this particular error. Then you have other errors that may exist in your mod (such as my issue with inability to connect that I originally came to report and was distracted). When I have 17 mods doing the exact same thing as this one is, on top of the 23 other sets of console spam from stuff actually working right that is overkill from many mods trying to honk their own horn my console logs is ~2.4 million lines long before I even open a world.
- I originally came to report my issue. As any good error reporter should, I was going through previously reported issues with similar titles or info that matched other errors I saw in my log to make sure my issue wasn't part of that issue. I saw that this issue was brushed off when it was in fact an issue, albeit an issue of annoyance. Perhaps being melodramatic due to frustration at seeing another dismissal from you regardless of the severity, just set me off due to previous experiences so very much so broken was an overstatement in a frustrated attempt to get my point across that it's an issue, wether you see it as such.
- this isn't this mod related but a brod statement I've seen made across your mods over time. Maybe not of late, but it's been your attitude in the past.
- this was in reference to suggestions or points I've made to assist in finding the issue on previous issues. again based on my previous experience in issues I did not create, but was commenting on in an attempt to provide additional information, was dismissed, and when I looked through code found that where I was kinda pointing was in fact the issue. I may not know exactly what the issue is because I don't fully understand code, you're absolutely right, but I've been pretty good at being able to tell where the issue likely is when I'm forced to look for it because I've been dismissed so I find a way to fix it myself.
- The block of text is about you. It's a vent of pent up frustration and animosity I've had towards you for years that finally bubbled to the surface because I happened to have a particularly crap month. You're right, it's not about anything.
- This is again based on past as my whole issue is purely about your attitude and not any particular issue with any mod. You have in the past clearly stated there's nothing wrong with your code, talk to them. Then a future update from you on a mod, not necessarily this one cuz I don't remember my reports anymore either, fixed the issue I was having, didn't mention my report so you didn't know it was fixed because you never said anything to verify on an open ticket. I know there's a lot of them and it's hard to keep track of them all. None of that's an issue but I have to assume based on all of that that you didn't even know that what you did fixed my issue. During the entire time not one update came out for the mod that your mod was having an issue against, and therefore it was clearly an issue with your code that you brushed off as another authors fault.
-  this entire portion was to give context as to how I knew it was your code not theirs when you bluntly and clearly stated it was. It had nothing to do with open or closed tickets. I couldn't care less about having a closed ticket as long as the issue gets resolved. See above bullet for a clearer headed completion of why that rabbit hole was followed.
- Finally I picked this issue on purpose to further emphasize the issue being not the reported issue nor having anything to do with any reported issue. And I thoroughly apologize to the OP as they just happen to be the catalyst of my rage volcano.
- you find forge inferior to the current platform you're using and therefore not worth your time to hear out people's issues about. You blanket statemented this is an issue caused by forge and made it appear that you didn't care enough to hear that person's complaint. Perhaps his was similar to my first bulleted complaint. But your bluntness and the way you brush it off as a non issue before they can even say why it's an issue makes these who may not feel as confident in their abilities in reporting feel silly for making a report in the first place so they won't even say why it's an issue for them in particular. That's what it did to me on my reports that were dismissed before I stopped caring what people thought of me.
- ok great. Did you say that? Give a small reassurance to the author that this isn't an issue. You likely wouldn't have gotten the second person reporting they're also having the issue if you'd have simply said this is code I put in because forge doesn't do things right. It will cause no issues to the game and is simply annoying. Is it as short and consise as "Yes, update forge to neoforge as it's a forge bug" but it sure makes me feel like I'm heard and not like I was told to go fuck myself for still using garbage forge. There's a large array of mods in my pack that haven't updated to neoforge that's quite entwined in the years of work I've done. You're asking me to abandon a large chunks of my life because you can't be bothered to hear why it's an issue for this person. I'm not entitled, I'm sick and tired of being ignored and dismissed at each and every turn I make considering the amount of time I take to make sure that I know that this issue belongs to this mod and trying to narrow down the specific circumstances to be told "I don't care." All of which is more a comment on the moding community as a whole of late than on you or me in particular.
- this was a reference to my issue that I was presenting, not the issue this post was about, which is the attitude you seem to continue to portray through your responses.

**Comment by MehVahdJukaar** [comment] 2024-11-20 12:16
- For this issue itself I will make the log lines be single log lines. The fact that they are more than 36 lines in your case is indeed an oversight.

- as for issues I had dismissed fixing themselves there had been 2 this month. One caused by creeper overhaul, which is caused by the same exact bug as this one and given the weird situation forge 1.20 is where people can't really update to neo sometimes, it was "fixed" the same way as this by just disabling that part. Another one was caused by lithium which was 100% their issue and was fixed in a new update of 1.21. before that happened however I was made aware that lithium had a mod facing API to disable some of its component and so I did, force disabling a piece of lithium via my configuration so that their code wouldn't cause issues. This one to as you can notice wasn't really a fix either. So no it wasn't "clearly a bug from my code". And even if there was an issue that was caused by my stuff it's very very likely that it was one of those that required a complicated interaction of mod things to happen where technically both parties are at fault. There was one like that recently too and a fix or workaround from either end could avoid it. For example I recently changed some code that inadvertently made a couple of issues caused by some random hard casts mods were having go away. This was done for a different reason and the issue on their end remains but it just so happens that it's not triggered anymore. The difference might seem slight but it's a big one
- forge as old forge IS inferior to neoforge. That's a fact as many bugs were fixed and many new systems added there (mainly talking about 1.21)

Finally regarding my attitude, if you had to deal with the amount of free technical support I have to deal on a daily basis you will understand. I used to be more down to earth but as time passed and quantity grew I started to be more and more direct and to the point in my replies. Some might find it efficient, others might find it harsh. That's also why it seems sometimes I'm just quickly reading through them, precisely because I am, I've seen so many that most of the times I know what kind of issue it is beforehand, or it's an already reported issue so I just say what the issue is directly. 
You could say I'm more concerned about dealing with issues rather than people reporting them which is sad but writing long replies like I am doing here takes a lot of time and energies which unfortunately I don't have so if my way of handling bugs made you feel frustrated I apologies but know that I don't have anything against any of you as why would I after all

**Comment by DelviousCrafts** [comment] 2024-11-20 16:40
Cool. I've said my piece. Based on your response you intend to make ZERO changes, rather than hearing someone out and thinking maybe I went to the other extreme with my responses. A touch more info when the error is negligable might be helpfu. I understand your reasoning behind that decision and I disagree with that reasoning. It was, after all, YOUR decision to make a several complicated mods and are annoyed when the public is the public and don't do the due diligence of reporting and punish everyone because of the average man. I'll simply remove the offending mods (yours) and never have to deal with any of it again. I will, at this point, happily do all the things you've done for my pack myself.

**Comment by MehVahdJukaar** [comment] 2024-11-20 20:42
Its your game, you are free to do what you want, install and uninstall all the mods you want, you dont have to go on boasting about what you can and cant do like it makes any diffecence to me.
I believe i have answered all your points yet you somehow still think im doing the community (or more specifically) you some sort of disservice and this at this point honestly i dont really get.
Also talking about annoyance, the only relevant thing here that annoys me is when some people found some instance and dont report it as that would just make a worse experience fo everybody. Annoyed is even an overstatement here, i would rather say that the ones that do report stuff are doing the community a service.
Also what things would I have donefor your pack? Not sure what you mean here.

Anyways i'm closing this issue as the new version that is already out has way shorter log lines, how they were meant to be, so this original issue here is solved. Not sure why you are stating you think i would be making zero changes when i literally just said the opposite in my reply before this

**Closed by MehVahdJukaar** 2024-11-20 20:42 UTC
Labels: bug, 1.20.1
