### ISSUE TITLE
[🐞]: [1.20.1] Crash every single time I launched the game

### ISSUE THREAD

**Issue by PanduC14** [MehVahdJukaar/Supplementaries#1287] opened 2024-12-22 01:33 UTC
### Before Continuing:

- [X] Check you are using the latest version of the mods and its dependencies
- [X] Always include a latest.log if you are crashing
- [ ] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1-FORGE

### Supplementaries Version

supplementaries-1.20-3.1.10

### Moonlight Lib Version

moonlight-1.20-2.13.41-forge

### Describe Issue

Here is my latest log:
[latest.log](https://github.com/user-attachments/files/18220489/latest.log)

Here is my crash report:
[crash-2024-12-21_21.37.36-client.txt](https://github.com/user-attachments/files/18220492/crash-2024-12-21_21.37.36-client.txt)

I was having problem every time I install supplementaries and when I launched the game it immediately crashed, I am using Fold Craft Launcher as my launcher, I hope the information is useful, hope you could fix this, thank you.

He is my (new) latest log, since the first one have issue with iris, here's is the one with no iris:

![fcl-latest4069250257409699938.zip](https://github.com/user-attachments/files/18260943/fcl-latest4069250257409699938.zip)

**Comment by MehVahdJukaar** [comment] 2024-12-22 14:28
I don't see anything related to supplementarirs. I just see stuff from iris

**Comment by Xelbayria** [comment] 2024-12-22 19:33
I can confirm what he said blc I saw the same thing in latest.log

**Comment by PanduC14** [comment] 2024-12-27 14:04
> I don't see anything related to supplementarirs. I just see stuff from iris

I don't use iris since it crashed my game, but to help here's my new latest log

![fcl-latest4069250257409699938.zip](https://github.com/user-attachments/files/18260932/fcl-latest4069250257409699938.zip)

**Comment by MehVahdJukaar** [comment] 2024-12-27 14:07
closing this as invalid as you are using optifine. Dont use mods with optifine. this is the reason. Terrible incompatible mod. Infact you have no reaso to use it at all in 2024

**Closed by MehVahdJukaar** 2024-12-27 14:07 UTC
Labels: bug, information, 1.20.1

**Comment by PanduC14** [comment] 2024-12-27 14:09
> closing this as invalid as you are using optifine. Dont use mods with optifine. this is the reason. Terrible incompatible mod. Infact you have no reaso to use it at all in 2024

Oh alright then, thank you🙏

**Comment by Xelbayria** [comment] 2024-12-27 18:51
You can check out [Notes on Optifine](https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Note%20on%20OptiFine.md)

there is another alternative mod of Optifine. There are other useful mods that can do bug-fix or improve the performance of Minecraft.
