### ISSUE TITLE
Flag Missing Texture

### ISSUE THREAD

**Issue by MaGames53812** [MehVahdJukaar/Supplementaries#299] opened 2022-08-09 20:56 UTC
The flag as an item and when placed down has the missing texture pattern
![JeiSupFlag](https://user-images.githubusercontent.com/110939089/183758335-ebf5cf34-d3ea-4dbc-96dc-b2ab183d92b6.png)
.
![2022-08-09_15 56 03](https://user-images.githubusercontent.com/110939089/183759852-07ae83f7-7507-4883-aba1-481e46619a8b.png)

**Comment by MehVahdJukaar** [comment] 2022-08-09 21:26
What version?

**Comment by MaGames53812** [comment] 2022-08-09 22:54
I fixed it, I had other mod texture packs above it, it was version 2.0.12 for Minecraft 1.19

**Comment by MehVahdJukaar** [comment] 2022-08-10 08:33
Hm still shouldn't have happened. What mod texture pack did you have on?

**Comment by MaGames53812** [comment] 2022-08-10 15:04
Infernal Expansion version 2.5.2

**Comment by MehVahdJukaar** [comment] 2022-08-10 18:02
are you sure Could you try adding back that texture pack and see if it happens again? I want to be sure its not an errorthat only happens at random

**Comment by MaGames53812** [comment] 2022-08-10 20:07
It may have been at random, I put the infernal expansion texture pack above supplementaries and the texture is fine

**Comment by MehVahdJukaar** [comment] 2022-08-11 06:17
Damn that's bad, I hate when stuff isn't easily repeatable. That has to be caused by a race issue and I'm not sure how to fix

**Comment by MehVahdJukaar** [comment] 2022-09-05 15:30
should have been fixed now

**Closed by MehVahdJukaar** 2022-09-05 15:30 UTC
